SyobonAction.exe: main.o loadg.o DxLib.o
	g++ -mwindows main.o loadg.o DxLib.o -lmingw32 -lstdc++ -lSDLmain -lSDL -lSDL_gfx -lSDL_image -lSDL_mixer -lSDL_ttf -o SyobonAction.exe

main.o:main.cpp
	g++ -mwindows -O2 -c main.cpp

loadg.o:loadg.cpp
	g++ -mwindows -O2 -c loadg.cpp

DxLib.o:DxLib.cpp
	g++ -mwindows -O2 -c DxLib.cpp
